name: art

env:
  ART_NAME: irvy

on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ART_NAME }}
        path: ./foo

  job2:
    name: job2 
    runs-on: ubuntu-latest
    needs: build 
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.ART_NAME }}

